In [1]:
import os
from pathlib import Path

import yaml
import pandas as pd

from bccd.dataset.parse_voc import parse_voc
from bccd.dataset.prepare_targets import prepare_regression_targets, create_yolo_split
from bccd.dataset.create_yolo_ds import voc_to_yolo

In [2]:
if os.getcwd().endswith('notebooks'):
    os.chdir('..')
print(f"Сейчас мы тут: {os.getcwd()}")

Сейчас мы тут: /Users/veronika_steklo/PycharmProjects/ML_NN_SSU/bccd

In [3]:
cfg = yaml.safe_load(open('configs/default.yaml'))
DATA_ROOT = Path(cfg['DATA_ROOT'])
CLASSES = cfg['CLASSES']

In [4]:
df = parse_voc(str(DATA_ROOT))
df.to_csv('dataset/voc_counts.csv', index=False)
df.head()

           image_id  WBC  RBC  Platelets
0  BloodImage_00315    1   10          1
1  BloodImage_00301    1   13          1
2  BloodImage_00117    1   10          2
3  BloodImage_00103    1   16          1
4  BloodImage_00088    1   10          2

In [5]:
Path('outputs').mkdir(exist_ok=True)

In [6]:
prepare_regression_targets(str(DATA_ROOT))
reg_df = pd.read_csv('dataset/regression_targets.csv')
reg_df.head()

                                          image_path  WBC  RBC  Platelets
0  ../data/BCCD_VOC/BCCD/JPEGImages/BloodImage_00...    1   10          1
1  ../data/BCCD_VOC/BCCD/JPEGImages/BloodImage_00...    1   13          1
2  ../data/BCCD_VOC/BCCD/JPEGImages/BloodImage_00...    1   10          2
3  ../data/BCCD_VOC/BCCD/JPEGImages/BloodImage_00...    1   16          1
4  ../data/BCCD_VOC/BCCD/JPEGImages/BloodImage_00...    1   10          2

In [7]:
voc_to_yolo(str(DATA_ROOT))
create_yolo_split(str(DATA_ROOT))

✅ VOC → YOLO conversion done

In [8]:
yolo_labels = Path('dataset/yolo/labels')
sample_files = list(yolo_labels.glob('*.txt'))[0]

print("\nПримеры YOLO-аннотаций (format: class_id xc yc w h):")
print(f"\n{sample_files.name}:")
print(sample_files.read_text().strip())

Примеры YOLO-аннотаций (format: class_id xc yc w h):

BloodImage_00015.txt:
0 0.395313 0.254167 0.337500 0.491667
1 0.610156 0.382292 0.117188 0.202083
1 0.626563 0.145833 0.146875 0.241667
1 0.765625 0.247917 0.156250 0.170833
1 0.917969 0.198958 0.157812 0.202083
1 0.760156 0.079167 0.160938 0.154167
1 0.728906 0.852083 0.173437 0.208333
1 0.500000 0.926042 0.168750 0.147917
1 0.105469 0.912500 0.207813 0.175000
1 0.080469 0.678125 0.157812 0.222917
1 0.177344 0.240625 0.160938 0.222917
1 0.467969 0.530208 0.160938 0.222917
1 0.230469 0.719792 0.176563 0.189583
1 0.940625 0.395833 0.118750 0.208333
2 0.490625 0.815625 0.071875 0.077083
1 0.669531 0.525000 0.173437 0.208333